name: Generate Snake Animation

on:
  schedule: # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hprakash1999
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to Main Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: main # 👈 now snake.svg goes into main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
